### PR TITLE
Upgrade advice for jmvc 3.2

### PR DESCRIPTION
**Pull request by tqwhite**
The things I had to do to make my app work with JMVC 3.2

### CODE REVIEW

**Comment by daffl** [comment]
Thanks for the thorough update. The thing is that some things, like the changes to Steal, Controller names and onDocument controllers are already mentioned at the beginning of this guide. It would be a great help if you could edit the existing paragraphs if you think they didn't explain it properly or missed something.

**Comment by tqwhite** [comment]
I'm willing to try but would like to suggest that it's not a good idea. 

The upgrade guide I wrote is procedural. It tells what to do about the changes that have been made. I think that's a different information context than the announcement style above. In addition, I think it's important to have the overview of changes that are being discussed before the discussion of what to do about it. That is, repetition is good for something like this.

In addition, it would be inappropriate in the change announcement section to remind people that they need to revise their controller class names. I have offered very practical advice based on careful note-taking. Combining the two kinds of information will, I believe, ruin the clarity of both of them.

Let me know what you think.

tqii

TQ White II
Website  tqwhite.com
Phone  708-763-0100

**Comment by daffl** [comment]
Well it was supposed to be more of a guide instead of just announcements (this is what the changelog is for). So it would be really interesting to get your input on what you think was missing or incomplete.

The reason why there is a more bullet point kind of list was because not everybody might be using all the features and migrating them in exactly the same order as e.g. you did. So the idea was to point everything out and then provide a more complete migration guide for each point.

**Comment by tqwhite** [comment]
We are pretty much on the same page for the intent as a guide. I see the value of point stuff out and then explain migration (and I really, really think it's needed). 

I will revisit and do a more thoughtful revision. See what I can figure out.

It will take a couple of days. This work thing is such a distraction. Damn boss.

best,
tqii

TQ White II
Website  tqwhite.com
Phone  708-763-0100

**Comment by daffl** [comment]
No worries, and thanks for helping out!

**Pull request merged**
