### PR TITLE
Completes #169

### PR DESCRIPTION
**Pull request by atomgroom**
Completes #169

### CODE REVIEW

**Comment by atomgroom** [comment]
@moschel This was merged, but why is it not live?

**Comment by moschel** [comment]
It looks like the commit is not in master anymore...I'll investigate

**Comment by moschel** [comment]
https://github.com/donejs/donejs/blob/master/docs/donejs.mustache#L241

It is, I'm confused.

**Comment by phillipskevin** [comment]
This is the one that @atomgroomdesign added: https://github.com/donejs/donejs/blob/master/docs/donejs.mustache#L285

The CI and Documentation ones are missing also. I can put them all back in with the change we're working on now.

**Comment by phillipskevin** [comment]
I think it was just a merge conflict with this change: https://github.com/donejs/donejs/commit/1fdd1956d166d18210cc7dbc6f23187e0e5009c4

**Pull request merged**
