### PR TITLE
Remove plug for Apple

### PR DESCRIPTION
**Pull request by leoj3n**
As much as I love Apple, this sentence is a bit convoluted, and it could actually rub some people the wrong way. The statement is more impactful when made standalone about DoneJS, in my opinion.

### CODE REVIEW

**Comment by matthewp** [comment]
I agree. 👍

**Comment by justinbmeyer** [comment]
Not sure I agree. I'd want to keep a metaphor here. Without it, this loses stickiness. Why would this rub people the wrong way?

**Comment by leoj3n** [comment]
Well, like I said, it's just my opinion. I've run into a lot of developers who are diabolically opposed to Apple, but they would still use DoneJS I'm sure of that. If you feel the need for a metaphor, and aren't just trying to say you emulate Apple culture or something, I think a more "accurate" or universal metaphor may exist.

**Comment by leoj3n** [comment]
*Think I meant "diametrically opposed"

**Comment by phillipskevin** [comment]
> Just as the Planeteers combine their powers to summon Captain Planet, DoneJS combines the powers of different technologies to summon unique advantages that you can only get from using an integrated solution.

captain planet

**Comment by leoj3n** [comment]
I knew I was going to get grilled for bikeshedding on this!

I like that @phillipskevin — You really should feel like a superhero when using DoneJS.

**Comment by matthewp** [comment]
What was decided here?

**Comment by chasenlehara** [comment]
We talked about it in [a contributors meeting](http://forums.donejs.com/t/donejs-contributors-meeting-2017-03-10/572/9). We discussed replacing the “plug” with a better metaphor that communicates the same idea.

**Comment by matthewp** [comment]
Is anyone working on this? I'd prefer to close PRs that aren't being worked on.

**Comment by leoj3n** [comment]
You can close it (didn't want it to stay open this long either). Was hoping
everyone would agree to remove the line and it would get closed fast that
way, but since there is an argument to keep it let's just keep it.

**Comment by matthewp** [comment]
Sorry it didn't work out :(

**Pull request closed without merging**
