### PR TITLE
add russian about.md file

### PR DESCRIPTION
**Pull request by xedoken**

### CODE REVIEW

**Comment by marshallswain** [comment]
@ilyavf Want to take a look at this?  I think you are the most qualified.  :)

**Comment by xedoken** [comment]
If translation will be ok, I can translate other pages from docs folder :)

**Comment by xedoken** [comment]
any news?

**Comment by matthewp** [comment]
Hey @xedoken I'll take a look at this tomorrow and get back with you. I don't know what/if we're doing anything to make this show up for Russian readers.

**Comment by ilyavf** [comment]
The translation looks good to me.

**Pull request merged**
