### PR TITLE
Chat guide automation

### PR DESCRIPTION
**Pull request by daffl**
This pull request uses the [chat-guide](https://github.com/donejs/chat-guide) automated test sources in the guide.

### CODE REVIEW

**Comment by daffl** [comment]
I still need to add the run to CI.

**Comment by daffl** [comment]
This is working locally for me on Windows but not on CI. I am not sure why. We may want to move those tests to our own infrastructure.

**Comment by justinbmeyer** [comment]
What do you think:

```
npm WARN invalid config access=undefined
npm WARN invalid config https-proxy=undefined
npm WARN invalid config Must be a full url with 'http://'
npm WARN invalid config init-author-url=undefined
npm WARN invalid config Must be a full url with 'http://'
npm WARN invalid config proxy=undefined
npm WARN invalid config Must be a full url with 'http://'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prefix" "-g"
```

means?

**Comment by daffl** [comment]
Where does that happen? The Windows VMs get stuck around

```
> websocket@1.0.22 install C:\projects\donejs\donejs-chat\node_modules\can-ssr\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\projects\donejs\donejs-chat\node_modules\can-ssr\node_modules\websocket>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
```

Which is where my Windows 7 had problems before moving installation into a separate step but it is now working.

**Comment by matthewp** [comment]
This closes #526

**Pull request merged**
